### ISSUE TITLE
About torch_geometric package

### ISSUE THREAD

**Issue by Quincy1994** [psp3dcg/GSAPool#1]
hi，your pepar is inspiring ! However, this repository your delievered seems to be imcoplete.  Did you upload torch_geometric package,  or how can I find the implemtation of your GSAPool network structure ?  I am  looking forward to your reply. Thank you.

**Comment by psp3dcg** [comment]
> hi，your pepar is inspiring ! However, this repository your delievered seems to be imcoplete. Did you upload torch_geometric package, or how can I find the implemtation of your GSAPool network structure ? I am looking forward to your reply. Thank you.
Hi, the torch_geometric is opensourced at https://github.com/rusty1s/pytorch_geometric, please install it as the website instructions. I hope it can be helpful~

**Comment by Quincy1994** [comment]
Wow, thank you !
